# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.               
          - ls -hal
          - apt-get update
          - apt-get -qq install git-ftp
          - apt-get -y install nodejs-legacy
          - apt-get -y install npm
          - npm set registry https://registry.npmjs.org/
          - npm install
          - npm build
          - ls