# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.               
          - ls -hal
          - apt-get update
          - apt-get -qq install git-ftp
          - apt-get -y install nodejs-legacy
          - apt-get -y install npm
          - npm install -g @angular/cli
          - npm set registry https://registry.npmjs.org/
          - npm install
          - npm build
          - git add -f .
          - git diff --cached --name-only
          - git config --global user.name "Igor Smyrnov"
          - git config --global user.email "smyrnovai@gmail.com"
          - git commit -m "builded"
          - ls
          - git ftp init -v --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://serwer1740022.home.pl/public_html/tracker